apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport
  namespace: wordpress
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 8080
    nodePort: 30008
  selector:
    app: wordpress